version: "3.9"

services:
  backend:
    build:
      context: ./property-inspection-backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Default=Host=localhost;Port=5433;Database=propertydb;Username=postgres;Password=postgres